config/routes.rb
Rails.application.routes.draw do
  resources :clearance_batches, only: [:new,:create] do
    resources :items, only: [:index]
  end
  resources :items, :only => :index
  root to: "clearance_batches#index"
end

app/models/clearance_batch.rb
class ClearanceBatch < ActiveRecord::Base

  has_many :items, :counter_cache => true

end

app/models/item.rb
class Item < ActiveRecord::Base

  validate :clearance_price_is_not_too_low, :if => :price_sold_changed? && :status_changed?, :on => :update
  validate :item_status_allows_clearancing, :if => :sold_at_changed?, :on => :update

  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")

  belongs_to :style
  belongs_to :clearance_batch
  alias_attribute :batch, :clearance_batch

  attr_accessor :being_clearanced

  scope :sellable, -> { where(status: 'sellable') }

  def clearance!
    Rails.logger.info "in clearance!"
    self.being_clearanced = true
    Rails.logger.info "self.being_clearanced = #{self.being_clearanced}"
    self.status = 'clearanced'
    self.price_sold = clearance_price
    self.sold_at = Time.zone.now
    self.save
  end

  def sellable?
    self.status == 'sellable'
  end

private

  def clearance_price
    self.style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE
  end

  def minimum_clearance_price
    self.style.minimum_clearance_price
  end

  def clearance_price_is_not_too_low
    if self.status == 'clearanced' && self.price_sold < minimum_clearance_price
      errors.add(:price_sold,"#{formatted_price} is too low for Item of style #{style.type}")
    end
  end

  def item_status_allows_clearancing
    Rails.logger.info('in item_status_allows_clearancing')
    previous_status = self.attribute_was('status')


    if previous_status != 'sellable' && self.status == 'clearanced'
      Rails.logger.info('adding error')
      errors.add(:status,"#{previous_status} can not be clearanced again")
    end
  end

  def formatted_price
    # Using number_to_currency helper here Violates MVC. We're ok with it here.
    ActionController::Base.helpers.number_to_currency(price_sold)
  end
end

app/models/style.rb
class Style < ActiveRecord::Base
  self.inheritance_column = :_type_disabled
  has_many :items

  def minimum_clearance_price
    type.in?(['Pants','Dress']) ? 5.00 : 2.00
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_batches_controller.rb
class ClearanceBatchesController < ApplicationController

  def index
    @batches  = ClearanceBatch.all
  end

  def new

  end

  def create
    clearancing_service = ClearancingService.new(uploaded_file)
    status = clearancing_service.process

    if status.counts[:success] > 0
      add_success "#{status.counts[:success]} items clearanced in batch #{status.batch.id}"
    else
      add_error "No new clearance batch was added"
    end

    if status.counts[:error] > 0
      add_error "#{status.counts[:error]} item ids raised errors and were not clearanced"
      add_error status.errors
    end

    index
    render action: :index
  end

private

  def uploaded_file
    if params[:'file-field']
      params[:'file-field'].tempfile
    else
      params[:item_ids]
    end
  end

  def add_success(messages)
    success_messages << messages
    success_messages.flatten
  end

  def add_error(messages)
    error_messages << messages
    error_messages.flatten
  end

  def success_messages
    @success_messages ||= []
  end

  def error_messages
    @error_messages ||= []
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if (batch_id = params[:clearance_batch_id])
      render_items_in_batch(batch_id)
    else
      render_all_items
    end
  end

  def render_items_in_batch(batch_id)
    @batch = ClearanceBatch.find(batch_id)
    @items = @batch.items
    render :template => 'items/items_in_clearance_batch'
  end

  def render_all_items
    @group_by = params[:group_by] || 'status'

    if @group_by == 'status'
      @groups = Item.order(:status).group_by{|i| i.status}
    else
      @groups = Item.order(:clearance_batch_id).group_by{|i| i.clearance_batch_id}
    end
    render :template => 'items/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clearance_batches/index.html.erb
<h2>Clearance Batches</h2>

<%= form_tag(clearance_batches_path, multipart: true, role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'file-field', 'Select batch file' %>
    <%= file_field_tag 'file-field', :id => 'file-field' %>
  </div>
  <%= button_tag 'upload batch file', :id => 'upload-batch-button' %>
<% end %>

<table id="batches-table">
  <thead>
    <tr>
      <th></th>
      <th>Date clearanced</th>
      <th>Number of items clearanced</th>
    </tr>
  </thead>
  <tbody>
    <%- @batches.each do |batch| -%>
      <tr id="batch-<%=batch.id%>" data-href="<%=clearance_batch_items_path(batch.id)%>" class='link-row'>
        <td>Clearance Batch <%= batch.id %></td>
        <td><%= l(batch.created_at, format: :short) %></td>
        <td><%= batch.items_count %></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/clearance_batches/new.html.erb
<%= form_tag clearance_batches_path, :method => 'post' do %>
<%=label_tag :item_ids, 'Item IDs' %>
<%=text_area_tag :item_ids, '', :id => 'item_ids' %>

<%=submit_tag 'Clearance', :id => 'clearance-item-ids' %>
<% end %>

app/views/items/_items.html.erb
<table id="items-table">
  <thead>
  <tr>
    <th>Item ID</th>
    <th>Type</th>
    <th>Name</th>
    <th>Color</th>
    <th>Sale Price</th>
  </tr>
  </thead>
  <tbody>
  <%- items.each do |item| -%>
    <tr id="item-<%=item.id%>">
      <td>Item <%=item.id%></td>
      <td><%=item.style.type%></td>
      <td><%=item.style.name%></td>
      <td><%=item.color%></td>
      <td><%=number_to_currency(item.price_sold)%></td>
    </tr>
  <%- end -%>
  </tbody>
</table>

app/views/items/index.html.erb
<h2>Browse Items</h2>


<%- if @group_by == 'status' -%>
  <div class="grouped-by">Grouped by Status</div>
  <div><%=link_to 'Group By Clearance Batch',items_path(:group_by => 'clearance_batch'), :id => 'group-by-status', :class => 'btn btn-mini' %></div>
<%- else -%>
  <div class="grouped-by">Grouped by Clearance Batch</div>
  <div><%=link_to 'Group By Status',items_path(:group_by => 'status'), :id => 'group-by-clearance-batch', :class => 'btn btn-mini' %>
<%- end -%>

<%- @groups.each do |group,items| -%>
  <div id="group-<%=group%>">
    <h3><%=group.to_s.titleize%></h3>
    <%= render :partial => 'items', :locals => {:items => items} %>
  </div>
<%- end -%>

<button type="button" class="btn btn-mini btn-primary">Mini button</button>

app/views/items/items_in_clearance_batch.html.erb
  <h2>Clearance Batch <%=@batch.id%> Items</h2>

  <%= render :partial => 'items', :locals => {:items => @items} %>

app/views/layouts/_messages.html.erb
<%- if messages.present? -%>
  <div class="alert alert-<%=message_type%>" role="alert">
    <%= messages.join('<br/>').html_safe %>
  </div>
<%- end -%>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Stitch Fix</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to 'Clearance Batch Upload', root_path %></li>
        <li><%=link_to 'Browse Items', items_path %></li>
        <li><%=link_to 'Scan Barcodes', new_clearance_batch_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clearancing Dashboard</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">

  <%= render :partial => 'layouts/nav' %>

  <h1>Stitch Fix Clearance Tool</h1>

  <%= render :partial => 'layouts/messages', :locals => {:messages => @success_messages, :message_type => 'info'} %>
  <%= render :partial => 'layouts/messages', :locals => {:messages => @error_messages, :message_type => 'danger'} %>

  <%= yield %>
</div>

</body>
</html>